framework:
    session:
        handler_id: null
        cookie_secure: auto      # "auto" pour éviter les problèmes en local (HTTP)
        cookie_samesite: lax     # "lax" pour permettre les redirections
        cookie_httponly: true
# framework:
#     session:
#         enabled: true
#     csrf_protection:
#         enabled: true
