monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - security # Security-related logs are logged in the dedicated "security" channel when it exists
    - contact # Contact form logs are logged in the dedicated "contact" channel when it exists
    - google_api # Google API logs are logged in the dedicated "google_api" channel when it exists
    - email # Email logs are logged in the dedicated "email" channel when it exists

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: "%kernel.logs_dir%/prod.log"
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        channels: [deprecation]
        path: "%kernel.logs_dir%/deprecation.log"
        formatter: monolog.formatter.json
      security:
        type: rotating_file
        path: "%kernel.logs_dir%/security.log"
        level: warning
        channels: [security]
        max_files: 90
      contact:
        type: rotating_file
        path: "%kernel.logs_dir%/contact.log"
        level: info
        channels: [contact]
        max_files: 90
      google_api:
        type: rotating_file
        path: "%kernel.logs_dir%/google_api.log"
        level: info
        channels: [google_api]
        max_files: 30
      email:
        type: rotating_file
        path: "%kernel.logs_dir%/email.log"
        level: info
        channels: [email]
        max_files: 30
