nelmio_security:
    clickjacking:
        paths:
            '^/.*': SAMEORIGIN
    content_type:
        nosniff: true
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
    forced_ssl:
        hsts_max_age: 31536000
        hsts_subdomains: true   
    permissions_policy:
        enabled: true
        directives:
            geolocation: ['self', 'https://cartes.app']
            microphone: []      # liste vide = désactivé
            camera: []
            payment: []
            usb: []