nelmio_security:
    clickjacking:
        paths:
            '^/.*': SAMEORIGIN
    content_type:
        nosniff: true
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
    forced_ssl:
        hsts_max_age: 31536000
        hsts_subdomains: true
    permissions_policy:
        enabled: true
        policies:
            geolocation: ['self', 'https://cartes.app']
            microphone: []
            camera: []
            payment: []
            usb: []
    csp:
        enabled: true
        report_endpoint:
            log_channel: security
            log_level: notice
            filters:
                domains: true
                schemes: true
                browser_bugs: true
                injected_scripts: true
        report:
            report-uri: /nelmio/csp/report
            default-src:
                - 'self'
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://cdn.jsdelivr.net'
                - 'https://unpkg.com'
                - 'https://www.google.com'      
                - 'https://www.gstatic.com' 
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://cdn.jsdelivr.net'
                - 'https://unpkg.com'
                - 'https://fonts.googleapis.com' 
            img-src:
                - 'self'
                - 'data:'
                - 'https://tile.openstreetmap.org'
                - 'https://*.tile.openstreetmap.org'
                - 'https://unpkg.com' 
            frame-src:
                - 'self'
                - 'https://calendar.google.com'
                - 'https://cartes.app'
                - 'https://www.google.com'
            font-src:
                - 'self'
                - 'data:'
                - 'https://fonts.gstatic.com' 
                - 'https://www.google.com'
            connect-src:
                - 'self'