framework:
  rate_limiter:
    forgot_password:
      policy: "sliding_window"
      limit: 3
      interval: "1 hour"
      cache_pool: 'cache.rate_limiter'
    drive_search:
      policy: "sliding_window"
      limit: 10
      interval: "1 minute"
      cache_pool: 'cache.rate_limiter'
    contact_form:
      policy: "sliding_window"
      limit: 2
      interval: "1 hour"
      cache_pool: 'cache.rate_limiter'
    comment_form:
      policy: 'sliding_window'
      limit: 3
      interval: '10 minutes'
      cache_pool: 'cache.rate_limiter'
    reset_password:
      policy: 'sliding_window'
      limit: 3
      interval: '1 hour'
      cache_pool: 'cache.rate_limiter'
