framework:
  rate_limiter:
    forgot_password:
      policy: "sliding_window"
      limit: 3
      interval: "1 hour"
    drive_search:
      policy: "sliding_window"
      limit: 20
      interval: "1 minute"
    contact_form:
      policy: "sliding_window"
      limit: 2
      interval: "1 hour"
    comment_form:
      policy: 'sliding_window'
      limit: 3
      interval: '10 minutes'
