  backup-before-author-fix[m
  backup-current[m
  backup-main-actuel[m
  historique-sauvegarde[m
  logo-readme[m
  main[m
  mini-carte-uMap[m
  modif-mineures[m
  pdf[m
  pdf-affiche-page-visiteur[m
  pdf-reconstruire[m
  readme[m
  readme15-05-2026[m
* [32mreadme2[m
  rectificationReadm-15-05-2026[m
  réajustements[m
  [31mremotes/origin/logo-readme[m
  [31mremotes/origin/main[m
  [31mremotes/origin/mini-carte-uMap[m
  [31mremotes/origin/modif-mineures[m
  [31mremotes/origin/pdf-affiche-page-visiteur[m
  [31mremotes/origin/pdf-reconstruire[m
  [31mremotes/origin/readme[m
  [31mremotes/origin/readme15-05-2026[m
  [31mremotes/origin/readme2[m
  [31mremotes/origin/rectificationReadm-15-05-2026[m
  [31mremotes/origin/réajustements[m
