controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

fm_elfinder:
  resource: "@FMElfinderBundle/Resources/config/routing.yaml"
oauth2:
  resource: "@LeagueOAuth2ServerBundle/Resources/config/routes.php"
  type: php

# Routes statiques (FOOTER : RGPD, mentions légales, etc.)
app_rgpd:
  path: /rgpd
  controller: App\Controller\PageController::rgpd
  methods: GET

app_legal:
  path: /mentions-legales
  controller: App\Controller\PageController::legal
  methods: GET

app_privacy:
  path: /politique-de-confidentialite
  controller: App\Controller\PageController::privacy
  methods: GET

app_cookies:
  path: /cookies
  controller: App\Controller\PageController::cookies
  methods: GET

# Routes dynamiques (slugs)
app_home:
  path: /
  controller: App\Controller\HomeController::home
  methods: GET

app_home_with_slug:
  path: /{slug}
  controller: App\Controller\HomeController::index
  methods: GET

nelmio_security:
    path:     /nelmio/csp/report
    defaults: { _controller: nelmio_security.csp_reporter_controller::indexAction }
    methods:  [POST]
